---
- name: Update All Packages on RedHat Systems
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Update Debian Packages on Debian Systems
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "*"
    state: latest
  when: ansible_os_family == 'Debian'